# Generated by Django 6.0 on 2025-12-04 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Номи китоб')),
                ('description', models.TextField(blank=True, verbose_name='Тавсифи мухтасар')),
                ('cover_image', models.ImageField(upload_to='book_covers/', verbose_name='Расми муқова')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Нархи китоб (сомонӣ)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Китоб',
                'verbose_name_plural': 'Китобҳо',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Сарлавҳаи боб')),
                ('content', models.TextField(verbose_name='Матни боб')),
                ('is_free', models.BooleanField(default=False, verbose_name='Ройгон аст?')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Тартиби ҷойгиршавӣ')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book', verbose_name='Китоб')),
            ],
            options={
                'verbose_name': 'Боб',
                'verbose_name_plural': 'Бобҳо',
                'ordering': ['order'],
            },
        ),
    ]
