# Generated by Django 5.2.4 on 2026-01-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_id_alter_chapter_id_alter_purchase_id_and_more'),
        ('books', '0008_chapter_is_premium'),
    ]

    operations = [
    ]
