# Generated by Django 5.1.5 on 2026-05-15 12:55

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Дар бораи мо', max_length=200, verbose_name='Сарлавҳа')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Матн')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Дар бораи мо',
                'verbose_name_plural': 'Дар бораи мо',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Номи китоб')),
                ('description', models.TextField(blank=True, verbose_name='Тавсифи мухтасар')),
                ('cover_image', models.ImageField(upload_to='book_covers/', verbose_name='Расми муқова')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Нархи китоб (сомонӣ)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Китоб',
                'verbose_name_plural': 'Китобҳо',
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='№ дар рӯйхат')),
                ('title', models.CharField(max_length=500, verbose_name='Сарлавҳа')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='legal_documents/', verbose_name='Файли PDF')),
                ('pdf_url', models.URLField(blank=True, help_text='Агар файл бор накунед, истифода баред: https://.../file.pdf', verbose_name='Ссылкаи PDF (URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаъол')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Санади меъёрию ҳуқуқӣ',
                'verbose_name_plural': 'Санадҳои меъёрию ҳуқуқӣ (Қоидаҳои ҳаракат дар роҳ)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Сарлавҳаи боб')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Матни боб')),
                ('is_free', models.BooleanField(default=False, verbose_name='Ройгон аст?')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум аст?')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Тартиби ҷойгиршавӣ')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book', verbose_name='Китоб')),
            ],
            options={
                'verbose_name': 'Боб',
                'verbose_name_plural': 'Бобҳо',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Номи нақша')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нарх')),
                ('days', models.PositiveIntegerField(verbose_name='Рӯзҳо')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаъол')),
                ('apple_product_id', models.CharField(blank=True, default='', help_text='Дар App Store Connect → In‑App Purchases Product ID (бо plan мепайвандад)', max_length=128, verbose_name='Apple IAP Product ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='books.book', verbose_name='Китоб')),
                ('chapters', models.ManyToManyField(blank=True, related_name='subscription_plans', to='books.chapter', verbose_name='Бобҳои дастрас')),
            ],
            options={
                'verbose_name': 'Нақшаи обуна',
                'verbose_name_plural': 'Нақшаҳои обуна',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Вақти харид')),
                ('expires_at', models.DateTimeField(verbose_name='Муҳлати анҷом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='books.subscriptionplan', verbose_name='Нақша')),
            ],
            options={
                'verbose_name': 'Обуна',
                'verbose_name_plural': 'Обунаҳо',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='AppleStoreTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Transaction ID')),
                ('original_transaction_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Original transaction ID')),
                ('product_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Product ID')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='JWS payload (decoded)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apple_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apple_transactions', to='books.subscriptionplan', verbose_name='Нақша')),
            ],
            options={
                'verbose_name': 'Apple IAP транзаксия',
                'verbose_name_plural': 'Apple IAP транзаксияҳо',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Маблағ')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=20, verbose_name='Ҳолат')),
                ('transaction_id', models.CharField(max_length=64, unique=True, verbose_name='ID-и транзаксия')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Тавсиф')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
            ],
            options={
                'verbose_name': 'Транзаксия',
                'verbose_name_plural': 'Транзаксияҳо',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Вақти харид')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='books.book', verbose_name='Китоб')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_books', to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
            ],
            options={
                'verbose_name': 'Китоби харидашуда',
                'verbose_name_plural': 'Китобҳои харидашуда',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='PurchasedChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Вақти харид')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нархи пардохташуда')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='books.chapter', verbose_name='Боб')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_chapters', to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
            ],
            options={
                'verbose_name': 'Боби харидашуда',
                'verbose_name_plural': 'Бобҳои харидашуда',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
