# Generated by Django 5.1.5 on 2026-06-05 11:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_transaction_smartpay_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='invoice_uuid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_provider',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='purchase_guide_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Қадамҳо барои хариди китоб/обуна. Дар барнома зери «Тарифҳо» намоиш дода мешавад.', verbose_name='Дастурамал: чӣ тавр харидан'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='purchase_guide_title',
            field=models.CharField(blank=True, default='Чӣ тавр харидан мумкин аст', max_length=200, verbose_name='Сарлавҳаи дастурамал (харид)'),
        ),
    ]
