# Generated by Cursor on 2026-01-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_id_alter_chapter_id_alter_purchase_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Номи нақша')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нарх')),
                ('days', models.PositiveIntegerField(verbose_name='Рӯзҳо')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаъол')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='books.book', verbose_name='Китоб')),
            ],
            options={
                'verbose_name': 'Нақшаи обуна',
                'verbose_name_plural': 'Нақшаҳои обуна',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Маблағ')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=20, verbose_name='Ҳолат')),
                ('transaction_id', models.CharField(max_length=64, unique=True, verbose_name='ID-и транзаксия')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Тавсиф')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
            ],
            options={
                'verbose_name': 'Транзаксия',
                'verbose_name_plural': 'Транзаксияҳо',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Вақти харид')),
                ('expires_at', models.DateTimeField(verbose_name='Муҳлати анҷом')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='books.subscriptionplan', verbose_name='Нақша')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
            ],
            options={
                'verbose_name': 'Обуна',
                'verbose_name_plural': 'Обунаҳо',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='subscription_plans', to='books.chapter', verbose_name='Бобҳои дастрас'),
        ),
    ]
