# Generated by Cursor on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_subscription_plans_and_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум аст?'),
        ),
    ]
