"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env', override=False)
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1uljb@9^*op6afg^!0%bym#s)rs9b$niqr!in$bc-(d1c-if(c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEMO_MODE = False
DEMO_OTP_MAP = {
    "+992921234567": "3002",
}
ALLOWED_HOSTS = [
    'books.1week.tj',
    'www.books.1week.tj',
    'books.payvandtrans.com',
    'www.books.payvandtrans.com',
    '62.60.239.81',
    '127.0.0.1',
    'localhost',
]
CSRF_TRUSTED_ORIGINS = [
    'https://books.1week.tj',
    'https://www.books.1week.tj',
    'https://books.payvandtrans.com',
    'http://books.payvandtrans.com',
]
AUTH_USER_MODEL = 'users.CustomUser'

# OsonSMS — аз .env ё муҳити сервер (дар production ҳатман .env)
OSONSMS_LOGIN = os.environ.get('OSONSMS_LOGIN', 'alijon3002').strip()
OSONSMS_HASH = os.environ.get('OSONSMS_HASH', 'f952f60ecc366c7ef161a1666bd681c2').strip()
OSONSMS_SENDER = os.environ.get('OSONSMS_SENDER', '1week.tj').strip()

# Telegram Login Widget (ихтиёрӣ)
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '').strip()

# OTP
OTP_EXPIRY_MINUTES = 5
OTP_RATE_LIMIT_SECONDS = 60

APP_NAME = 'Ҳуқуқи ронанда'

# Apple IAP: дар production ҳатман APPLE_BUNDLE_ID-и воқеии iOS-ро дар муҳит ё .env гузоред
_apple_bundle_id = os.environ.get('APPLE_BUNDLE_ID', '').strip()
if DEBUG:
    APPLE_BUNDLE_ID = _apple_bundle_id or 'com.bookkhuquqronanda.week'
else:
    if not _apple_bundle_id:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            'Production: танзим кунед муҳити APPLE_BUNDLE_ID (Bundle ID аз Apple Developer / Xcode).'
        )
    APPLE_BUNDLE_ID = _apple_bundle_id

# SmartPay Settings
SMARTPAY_API_TOKEN = 'def4e0372504f712a035a17ba570e42fadfb6ba9d0029df9639267a246936e8f'
SMARTPAY_API_URL = 'https://sandbox.smartpay.tj/api/merchant/invoices/'
SMARTPAY_RETURN_URL = 'https://1week.tj/success'
SMARTPAY_WEBHOOK_TOKEN = '4eed94124c86b03b9cf772a32accc2ad094f69656abfa0ce1bdeb7f66c882f0'

# Dushanbe City Payment Gateway Settings
DC_MERCHANT_ID = '10100002'
DC_PASSWORD = '987003002a'  # Иваз кардани ин ба пароли ҳақиқии шумо
DC_PAYMENT_URL = 'https://acquire.dushanbecity.tj/createOrder.jsp'
# Барои callback URL-ҳо - дар production инро ба домени ҳақиқии шумо тағйир диҳед
# Барои телефони ҳақиқӣ - IP-и локалии компютерро истифода мекунем
DC_BASE_URL = 'http://192.168.0.101:8000'  # Дар production: 'https://yourdomain.com'


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',  # Барои CORS (Flutter Web)
    'books',
    'users',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware бояд дар боло бошад
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'books_db',       # Номи базаи нав
        'USER': 'books_db',       # Номи юзери нав
        'PASSWORD': 'hkxCZjhhwwXLxebT',  # Ҳамон пароле ки дар расм буд
        'HOST': '127.0.0.1',             # Local Server
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Dushanbe'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Танзимоти CKEditor
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

# Танзимоти асосӣ барои намуди редактор
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',  # Ҳамаи инструменташро нишон диҳад (Bold, Italic, Table, Image)
        'height': 300,
        'width': '100%',
    },
}

# Танзимоти CORS барои Flutter Web
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5000",
    "http://127.0.0.1:5000",
     "https://books.1week.tj",
    "https://books.payvandtrans.com",
    "http://books.payvandtrans.com",
    
]

# Барои development - иҷоза медиҳад, ки ҳамаи доменҳо дастрас бошанд
CORS_ALLOW_ALL_ORIGINS = True  # Танҳо барои development! Дар production инро false кунед

# Иҷоза додани header-ҳо
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Иҷоза додани method-ҳо
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get(
    'MEDIA_ROOT',
    os.path.join(BASE_DIR, 'media'),
)

# PDF-ҳои «Қоидаҳои ҳаракат дар роҳ» — бевосита дар ин папка (бе /media/)
# Сервер: /www/wwwroot/books.payvandtrans.com/legal_documents
LEGAL_DOCUMENTS_ROOT = os.environ.get(
    'LEGAL_DOCUMENTS_ROOT',
    os.path.join(BASE_DIR, 'legal_documents'),
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Барои development - дар production тағйир диҳед
    ],
}